### ISSUE TITLE
One 3424234234123123fawefwaef

### ISSUE THREAD

**Issue by jclem** [jclem/test#6]
- awefwa
awefawef
- 1221

**Comment by jclem** [comment]
@jclem

**Comment by olivia** [comment]
123

**Comment by jclem** [comment]
test

**Comment by pmarsceill** [comment]
:wave:

**Comment by pmarsceill** [comment]
Just testing how fast I can comment here... It would be cool if <kbd>command</kbd> + <kbd>Enter</kbd> submitted the comment, so I didn't have to click the <kbd>Comment</button>

**Comment by jclem** [comment]
This is great see also issue #2
